# Generated by Django 5.1.1 on 2024-10-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_remove_post_image_name_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
    ]
