# Generated by Django 5.1.1 on 2024-10-31 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0010_comment_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
