# Generated by Django 5.1.1 on 2024-11-11 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0012_alter_post_content_alter_post_excerpt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
